@startuml

enum healthState {
IDEL = 0
DAMAGE = 1
DEAD = 2
}

class Packy extends Phaser.Scene{
healState : healthState
_health : number
_coin : number
_moveSpeed : number

.. getter ..
+ health()

.. setter ..
+ health()
+ coin()

+ move()
}
note left of Packy::_coin
    one coin has a 3 health
end note

@enduml